export const domains = [
  "fitness",
  "accommodation-booking",
  "healthcare",
  "mining",
  "social-media",
];

export const dimensions = [
  "economic",
  "individual",
  "social",
  "environmental",
  "technical",
];

export const qualityAttributes = [
  "availability",
  "deployability",
  "energy-efficiency",
  "integrability",
  "modifiability",
  "performance",
  "safety",
  "security",
  "testability",
  "usability",
];

export const designPatterns = [
  "active-redundancy",
  "triple-modular-redundancy",
  "microservices-architecture",
  "blue-green-deployment",
  "kill-abnormal-tasks",
  "service-oriented-architecture",
  "plug-in-pattern",
  "load-balancer",
  "monitor-actuator",
  "intrusion-prevention-system",
  "dependency-injection",
  "strategy-pattern",
  "model-view-controller",
  "observer-pattern",
];

export const dimensionScoresTable = [
  {
    domain: "fitness",
    scores: {
      economic: 6,
      individual: 10,
      social: 7,
      environmental: 6,
      technical: 8,
    },
  },
  {
    domain: "accommodation-booking",
    scores: {
      economic: 9,
      individual: 7,
      social: 8,
      environmental: 8,
      technical: 6,
    },
  },
  {
    domain: "healthcare",
    scores: {
      economic: 7,
      individual: 9,
      social: 10,
      environmental: 6,
      technical: 8,
    },
  },
  {
    domain: "mining",
    scores: {
      economic: 8,
      individual: 5,
      social: 7,
      environmental: 10,
      technical: 9,
    },
  },
  {
    domain: "social-media",
    scores: {
      economic: 7,
      individual: 6,
      social: 10,
      environmental: 7,
      technical: 8,
    },
  },
  {
    domain: "E-commerce Platform",
    scores: {
      economic: 10,
      individual: 6,
      social: 7,
      environmental: 9,
      technical: 8,
    },
  },
  {
    domain: "Educational Platform",
    scores: {
      economic: 7,
      individual: 8,
      social: 10,
      environmental: 7,
      technical: 8,
    },
  },
];

export const qualityAttributesScoresTable = [
  {
    domain: "fitness",
    scores: {
      availability: 8,
      deployability: 6,
      "energy-efficiency": 7,
      integrability: 6,
      modifiability: 8,
      performance: 9,
      safety: 6,
      security: 8,
      testability: 7,
      usability: 10,
    },
  },
  {
    domain: "accommodation-booking",
    scores: {
      availability: 9,
      deployability: 8,
      "energy-efficiency": 6,
      integrability: 9,
      modifiability: 8,
      performance: 9,
      safety: 8,
      security: 9,
      testability: 8,
      usability: 9,
    },
  },
  {
    domain: "healthcare",
    scores: {
      availability: 9,
      deployability: 7,
      "energy-efficiency": 6,
      integrability: 7,
      modifiability: 7,
      performance: 8,
      safety: 10,
      security: 10,
      testability: 8,
      usability: 9,
    },
  },
  {
    domain: "mining",
    scores: {
      availability: 10,
      deployability: 7,
      "energy-efficiency": 8,
      integrability: 8,
      modifiability: 9,
      performance: 8,
      safety: 10,
      security: 9,
      testability: 7,
      usability: 6,
    },
  },
  {
    domain: "social-media",
    scores: {
      availability: 8,
      deployability: 7,
      "energy-efficiency": 6,
      integrability: 8,
      modifiability: 7,
      performance: 8,
      safety: 7,
      security: 10,
      testability: 8,
      usability: 10,
    },
  },
  {
    domain: "E-commerce Platform",
    scores: {
      availability: 9,
      deployability: 8,
      "energy-efficiency": 7,
      integrability: 8,
      modifiability: 7,
      performance: 9,
      safety: 7,
      security: 8,
      testability: 8,
      usability: 9,
    },
  },
  {
    domain: "Educational Platform",
    scores: {
      availability: 8,
      deployability: 7,
      "energy-efficiency": 6,
      integrability: 7,
      modifiability: 8,
      performance: 8,
      safety: 7,
      security: 8,
      testability: 9,
      usability: 10,
    },
  },
];

export const designPatternsScoresTable = [
  {
    qualityAttribute: "availability",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "deployability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 1,
      "blue-green-deployment": 1,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "energy-efficiency",
    scores: {
      "active-redundancy": -1,
      "triple-modular-redundancy": -1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "integrability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 1,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 1,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "modifiability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 1,
      "plug-in-pattern": 1,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 1,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "performance",
    scores: {
      "active-redundancy": -1,
      "triple-modular-redundancy": -1,
      "microservices-architecture": -1,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": -1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 1,
      "monitor-actuator": 0,
      "intrusion-prevention-system": -1,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": -1,
      "observer-pattern": -1,
    },
  },
  {
    qualityAttribute: "safety",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 1,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "security",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 1,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "testability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 1,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 1,
      "strategy-pattern": 1,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "usability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": -1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 1,
      "observer-pattern": 1,
    },
  },
];

export const dasWeight = 0.4;
export const sqcsWeight = 0.4;
export const dpcsWeight = 0.2;
