export const domains = [
  "fitness",
  "accommodation-booking",
  "healthcare",
  "mining",
  "social-media",
];

export const dimensions = [
  "economic",
  "individual",
  "social",
  "environmental",
  "technical",
];

export const qualityAttributes = [
  "availability",
  "deployability",
  "energy-efficiency",
  "integrability",
  "modifiability",
  "performance",
  "safety",
  "security",
  "testability",
  "usability",
];

export const designPatterns = [
  "active-redundancy",
  "triple-modular-redundancy",
  "microservices-architecture",
  "blue-green-deployment",
  "kill-abnormal-tasks",
  "service-oriented-architecture",
  "plug-in-pattern",
  "load-balancer",
  "monitor-actuator",
  "intrusion-prevention-system",
  "dependency-injection",
  "strategy-pattern",
  "model-view-controller",
  "observer-pattern",
];

export const dimensionScoresTable = [
  {
    domain: "fitness",
    scores: {
      economic: 5.625,
      individual: 8.333,
      social: 7.875,
      environmental: 5,
      technical: 5.222,
    },
  },
  {
    domain: "accommodation-booking",
    scores: {
      economic: 7.556,
      individual: 6.889,
      social: 7.444,
      environmental: 7.111,
      technical: 6.1,
    },
  },
  {
    domain: "healthcare",
    scores: {
      economic: 6.9,
      individual: 8.7,
      social: 7.4,
      environmental: 5.8,
      technical: 7.8,
    },
  },
  {
    domain: "mining",
    scores: {
      economic: 7.778,
      individual: 6.778,
      social: 5.333,
      environmental: 8.444,
      technical: 8.444,
    },
  },
  {
    domain: "social-media",
    scores: {
      economic: 6.889,
      individual: 8,
      social: 9,
      environmental: 5.667,
      technical: 7.556,
    },
  },
];

export const qualityAttributesScoresTable = [
  {
    domain: "fitness",
    scores: {
      availability: 7.556,
      deployability: 6.333,
      "energy-efficiency": 6.444,
      integrability: 7.111,
      modifiability: 7.778,
      performance: 7.889,
      safety: 7.111,
      security: 6.667,
      testability: 6.375,
      usability: 9.5,
    },
  },
  {
    domain: "accommodation-booking",
    scores: {
      availability: 8.8,
      deployability: 7.5,
      "energy-efficiency": 6.1,
      integrability: 7.2,
      modifiability: 7.4,
      performance: 8.7,
      safety: 7.1,
      security: 8.5,
      testability: 6.6,
      usability: 9.2,
    },
  },
  {
    domain: "healthcare",
    scores: {
      availability: 9.8,
      deployability: 7.7,
      "energy-efficiency": 5.4,
      integrability: 7.8,
      modifiability: 6.5,
      performance: 8.3,
      safety: 9.1,
      security: 9.1,
      testability: 7.7,
      usability: 9.2,
    },
  },
  {
    domain: "mining",
    scores: {
      availability: 8.778,
      deployability: 8.333,
      "energy-efficiency": 8.667,
      integrability: 7,
      modifiability: 6.444,
      performance: 8.111,
      safety: 8.889,
      security: 8.125,
      testability: 8.333,
      usability: 8.556,
    },
  },
  {
    domain: "social-media",
    scores: {
      availability: 8.111,
      deployability: 7.889,
      "energy-efficiency": 7,
      integrability: 8.111,
      modifiability: 8.444,
      performance: 7.889,
      safety: 7.444,
      security: 9.333,
      testability: 7.333,
      usability: 9.667,
    },
  },
];

export const designPatternsScoresTable = [
  {
    qualityAttribute: "availability",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "deployability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 1,
      "blue-green-deployment": 1,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "energy-efficiency",
    scores: {
      "active-redundancy": -1,
      "triple-modular-redundancy": -1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "integrability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 1,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 1,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "modifiability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 1,
      "plug-in-pattern": 1,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 1,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "performance",
    scores: {
      "active-redundancy": -1,
      "triple-modular-redundancy": -1,
      "microservices-architecture": -1,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": -1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 1,
      "monitor-actuator": 0,
      "intrusion-prevention-system": -1,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": -1,
      "observer-pattern": -1,
    },
  },
  {
    qualityAttribute: "safety",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 1,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "security",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 1,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "testability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 1,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 1,
      "strategy-pattern": 1,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "usability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": -1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 1,
      "observer-pattern": 1,
    },
  },
];

export const dasWeight = 0.36;
export const sqcsWeight = 0.36;
export const dpcsWeight = 0.28;
