export const domains = [
  "fitness",
  "accommodation-booking",
  "healthcare",
  "mining",
  "social-media",
];

export const dimensions = [
  "economic",
  "individual",
  "social",
  "environmental",
  "technical",
];

export const qualityAttributes = [
  "availability",
  "deployability",
  "energy-efficiency",
  "integrability",
  "modifiability",
  "performance",
  "safety",
  "security",
  "testability",
  "usability",
];

export const designPatterns = [
  "active-redundancy",
  "triple-modular-redundancy",
  "microservices-architecture",
  "blue-green-deployment",
  "kill-abnormal-tasks",
  "service-oriented-architecture",
  "plug-in-pattern",
  "load-balancer",
  "monitor-actuator",
  "intrusion-prevention-system",
  "dependency-injection",
  "strategy-pattern",
  "model-view-controller",
  "observer-pattern",
];

export const dimensionScoresTable = [
  {
    domain: "fitness",
    scores: {
      economic: 6,
      individual: 9.75,
      social: 8.75,
      environmental: 5.25,
      technical: 5.5,
    },
  },
  {
    domain: "accommodation-booking",
    scores: {
      economic: 8.2,
      individual: 7.6,
      social: 7.8,
      environmental: 7.4,
      technical: 6.6,
    },
  },
  {
    domain: "healthcare",
    scores: {
      economic: 7.6,
      individual: 9.8,
      social: 8.2,
      environmental: 6.2,
      technical: 8.2,
    },
  },
  {
    domain: "mining",
    scores: {
      economic: 8.25,
      individual: 8.25,
      social: 5.5,
      environmental: 9.5,
      technical: 9.25,
    },
  },
  {
    domain: "social-media",
    scores: {
      economic: 7.5,
      individual: 9,
      social: 9.75,
      environmental: 5.5,
      technical: 8,
    },
  },
];

export const qualityAttributesScoresTable = [
  {
    domain: "fitness",
    scores: {
      availability: 8.5,
      deployability: 6.5,
      "energy-efficiency": 6.25,
      integrability: 7.75,
      modifiability: 8,
      performance: 8,
      safety: 6.75,
      security: 6.75,
      testability: 6.25,
      usability: 9.5,
    },
  },
  {
    domain: "accommodation-booking",
    scores: {
      availability: 8.8,
      deployability: 7.4,
      "energy-efficiency": 5.2,
      integrability: 7.2,
      modifiability: 7.6,
      performance: 9,
      safety: 7,
      security: 9,
      testability: 6.8,
      usability: 9.4,
    },
  },
  {
    domain: "healthcare",
    scores: {
      availability: 9.8,
      deployability: 7.4,
      "energy-efficiency": 4.4,
      integrability: 8,
      modifiability: 6.6,
      performance: 8.2,
      safety: 9.4,
      security: 9.6,
      testability: 7.2,
      usability: 9.2,
    },
  },
  {
    domain: "mining",
    scores: {
      availability: 8.75,
      deployability: 8.5,
      "energy-efficiency": 9,
      integrability: 6.75,
      modifiability: 6.5,
      performance: 8.25,
      safety: 9.5,
      security: 8,
      testability: 8.25,
      usability: 8.75,
    },
  },
  {
    domain: "social-media",
    scores: {
      availability: 7.75,
      deployability: 7.75,
      "energy-efficiency": 6.5,
      integrability: 8.25,
      modifiability: 8.75,
      performance: 7.75,
      safety: 7.25,
      security: 9.75,
      testability: 7.5,
      usability: 9.75,
    },
  },
];

export const designPatternsScoresTable = [
  {
    qualityAttribute: "availability",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "deployability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 1,
      "blue-green-deployment": 1,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "energy-efficiency",
    scores: {
      "active-redundancy": -1,
      "triple-modular-redundancy": -1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "integrability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 1,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 1,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "modifiability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 1,
      "plug-in-pattern": 1,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 1,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "performance",
    scores: {
      "active-redundancy": -1,
      "triple-modular-redundancy": -1,
      "microservices-architecture": -1,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": -1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 1,
      "monitor-actuator": 0,
      "intrusion-prevention-system": -1,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": -1,
      "observer-pattern": -1,
    },
  },
  {
    qualityAttribute: "safety",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 1,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "security",
    scores: {
      "active-redundancy": 1,
      "triple-modular-redundancy": 1,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 1,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "testability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": 0,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 1,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 1,
      "strategy-pattern": 1,
      "model-view-controller": 0,
      "observer-pattern": 0,
    },
  },
  {
    qualityAttribute: "usability",
    scores: {
      "active-redundancy": 0,
      "triple-modular-redundancy": 0,
      "microservices-architecture": 0,
      "blue-green-deployment": 0,
      "kill-abnormal-tasks": -1,
      "service-oriented-architecture": 0,
      "plug-in-pattern": 0,
      "load-balancer": 0,
      "monitor-actuator": 0,
      "intrusion-prevention-system": 0,
      "dependency-injection": 0,
      "strategy-pattern": 0,
      "model-view-controller": 1,
      "observer-pattern": 1,
    },
  },
];

export const dasWeight = 0.4;
export const sqcsWeight = 0.4;
export const dpcsWeight = 0.2;
